from alembic import command
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, create_async_engine
from sqlalchemy.pool import NullPool

from ledger_api.data.base import Base
from ledger_api.data.models import Account, Ledger
from ledger_api.domain.account import AccountKind
from ledger_api.domain.currency import Currency
from tests.database import (
    configured_database_url,
    disposable_database_url,
    recreate_database,
    run_alembic,
)

LEDGER_TABLES = {"users", "ledgers", "accounts", "transactions", "ledger_entries"}


async def _public_tables(engine: AsyncEngine) -> set[str]:
    async with engine.connect() as connection:
        rows = await connection.execute(
            text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        )
        return set(rows.scalars())


async def _public_functions(engine: AsyncEngine) -> set[str]:
    async with engine.connect() as connection:
        rows = await connection.execute(
            text(
                "SELECT p.proname FROM pg_proc p "
                "JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public'"
            )
        )
        return set(rows.scalars())


async def test_migrations_upgrade_downgrade_and_upgrade_again() -> None:
    # A database of its own: downgrading the shared test database would break other tests.
    server_url = configured_database_url()
    url = disposable_database_url(server_url, "_migrations")
    assert url.database is not None
    await recreate_database(server_url, url.database)
    engine = create_async_engine(url, poolclass=NullPool)
    try:
        await run_alembic(engine, lambda config: command.upgrade(config, "head"))
        assert await _public_tables(engine) == LEDGER_TABLES | {"alembic_version"}

        await run_alembic(engine, lambda config: command.downgrade(config, "base"))
        assert await _public_tables(engine) == {"alembic_version"}
        assert await _public_functions(engine) == set()

        await run_alembic(engine, lambda config: command.upgrade(config, "head"))
        assert await _public_tables(engine) == LEDGER_TABLES | {"alembic_version"}
    finally:
        await engine.dispose()


async def test_models_match_migrations(engine: AsyncEngine) -> None:
    # Raises AutogenerateDiffsDetected if the models and the migrated schema have drifted
    # (tables, columns, types, nullability, foreign keys, unique constraints, indexes).
    await run_alembic(engine, command.check)


async def test_constraint_and_index_names_match_models(engine: AsyncEngine) -> None:
    # alembic check ignores CHECK constraints and does not compare names. Names matter: tests
    # and error handling identify violated rules by them.
    expected = {
        str(name)
        for table in Base.metadata.sorted_tables
        for name in [c.name for c in table.constraints] + [i.name for i in table.indexes]
    }
    async with engine.connect() as connection:
        rows = await connection.execute(
            text(
                "SELECT c.conname FROM pg_constraint c "
                "JOIN pg_namespace n ON n.oid = c.connamespace "
                # Skip constraint triggers ('t') and, since PostgreSQL 18, NOT NULL ('n'):
                # nullability is already compared by alembic check.
                "WHERE n.nspname = 'public' AND c.contype NOT IN ('t', 'n') "
                "UNION "
                "SELECT indexname FROM pg_indexes "
                "WHERE schemaname = 'public' AND tablename <> 'alembic_version'"
            )
        )
        actual = set(rows.scalars()) - {"alembic_version_pkc"}

    assert actual == expected


async def test_seeded_ledgers_are_exactly_the_supported_currencies(
    db_session: AsyncSession,
) -> None:
    currencies = (await db_session.scalars(text("SELECT currency FROM ledgers"))).all()

    assert sorted(currencies) == sorted(Currency)


async def test_every_ledger_has_one_settlement_account_with_zero_balance(
    db_session: AsyncSession,
) -> None:
    ledgers = (await db_session.scalars(select(Ledger))).all()
    system_accounts = (
        await db_session.scalars(select(Account).where(Account.kind == AccountKind.SYSTEM))
    ).all()

    assert len(system_accounts) == len(ledgers) == len(Currency)
    rows = (
        await db_session.execute(
            text(
                "SELECT l.currency, a.user_id, a.balance_minor FROM accounts a "
                "JOIN ledgers l ON l.id = a.ledger_id WHERE a.kind = 'system'"
            )
        )
    ).all()
    assert sorted(rows) == sorted((currency.value, None, 0) for currency in Currency)
