"""Order ledger entries by a database-assigned sequence number (ADR 0012).

Statements need each account's entries in commit order. Neither existing column gives it:
transactions.created_at is the transaction's start time (taken before it waited for a lock),
and the UUIDv7 id is generated by the application at millisecond resolution, so two processes
can order it differently from the commits.

sequence_number is a BIGINT identity with CACHE 1 (strictly increasing across sessions). A
posting draws it while it holds the row lock of every account it touches, and keeps that lock
until COMMIT, so for any one account sequence order equals commit order. Across different
accounts it implies nothing. The values have gaps (rolled-back postings consume numbers) and
are never exposed: they would reveal how many entries other accounts post.

Existing rows are numbered in UUIDv7 id order. That is best-effort only: before this revision
no commit order was recorded. Backfilling is an UPDATE of an append-only table, so the
immutability trigger is disabled for that one statement, inside this migration's
transaction (precedent: 0002).

(account_id, sequence_number) is unique and replaces the (account_id, id) index: it serves
statements, keyset pagination and reconciliation.

Like 0001, literals are hard-coded: a migration is a frozen snapshot.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-10 09:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Separate statements: asyncpg executes one command per prepared statement.
BACKFILL_SEQUENCE_NUMBERS = [
    "ALTER TABLE ledger_entries DISABLE TRIGGER ledger_entries_immutable",
    """
    UPDATE ledger_entries e
       SET sequence_number = numbered.position
      FROM (SELECT id, row_number() OVER (ORDER BY id) AS position FROM ledger_entries) numbered
     WHERE e.id = numbered.id
    """,
    "ALTER TABLE ledger_entries ENABLE TRIGGER ledger_entries_immutable",
]

MAKE_IDENTITY = [
    """
    ALTER TABLE ledger_entries
        ALTER COLUMN sequence_number ADD GENERATED ALWAYS AS IDENTITY (CACHE 1)
    """,
    # New entries continue after the backfilled ones (the next value is max + 1).
    """
    SELECT setval(
        pg_get_serial_sequence('ledger_entries', 'sequence_number'),
        coalesce((SELECT max(sequence_number) FROM ledger_entries), 0) + 1,
        false
    )
    """,
]


def upgrade() -> None:
    op.add_column("ledger_entries", sa.Column("sequence_number", sa.BigInteger(), nullable=True))
    for statement in BACKFILL_SEQUENCE_NUMBERS:
        op.execute(statement)
    op.alter_column("ledger_entries", "sequence_number", nullable=False)
    for statement in MAKE_IDENTITY:
        op.execute(statement)
    op.create_unique_constraint(
        op.f("uq_ledger_entries_account_id_sequence_number"),
        "ledger_entries",
        ["account_id", "sequence_number"],
    )
    op.drop_index(op.f("ix_ledger_entries_account_id_id"), table_name="ledger_entries")


def downgrade() -> None:
    op.create_index(op.f("ix_ledger_entries_account_id_id"), "ledger_entries", ["account_id", "id"])
    op.drop_constraint(
        op.f("uq_ledger_entries_account_id_sequence_number"), "ledger_entries", type_="unique"
    )
    # Dropping an identity column drops its sequence; DROP COLUMN fires no row triggers.
    op.drop_column("ledger_entries", "sequence_number")
